### ISSUE TITLE
Install version does not exist

### ISSUE THREAD

**Issue by shambu1818** [Mynima/Ravencoin_Node_RaspberryPi#2]
When I am trying to type the version to install, no matter what version I use the return says that version does not exist.  I tried 4.3.2.1, 4.3.2.0, 4.3.2, 4.3.1...

I used this install 2 weeks ago successfully, and I am repeating that process.  I noticed the new updates in the last 24 hours.  I wonder if that broke something.

**Comment by Mynima** [comment]
I've now reverted the updates I made previously. Please check that the versions exist in the relevant release location as well.

https://github.com/RavenProject/Ravencoin/releases/tag/v4.3.1

This is the last release with a "-arm-linux-gnueabihf.tar.gz" file available.

**Comment by shambu1818** [comment]
I can confirm that it will install 4.3.1.  Choosing 4.3.2.1, 4.3.2, 4.3.2.0 all result in "Version x.x.x.x does not exist, please try again.”

Sorry to be a pain.  Just figured you would want to know.  Thank you for creating this software.  It’s a huge help to novices like me.  Thanks!

sdh

**Comment by Mynima** [comment]
Not a pain at all, thanks for pointed out the issue, I should have tested it better before releasing it.
